name: Bug report
description: Report incorrect or unexpected behavior of Azure
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/azurebot
  - type: input
    id: command
    attributes:
      label: Command
      description: Provide the command name which is causing this bug/issue
      placeholder: inventory
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible. The commands used, replies, button/reaction clicks etc. Order matters.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce the issue:
        1. use command
        2. observe behavior
        3. current outcome
        4. expected outcome
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
