name: Bug report
description: Report incorrect or unexpected behavior of Azure
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/azurebot
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: |
        Describe the issue in as much detail as possible.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        Steps to reproduce the issue:
        1. use command
        2. observe behavior
        3. current outcome
        4. expected outcome
    validations:
      required: true
  - type: textarea
    id: actions
    attributes:
      label: Actions
      description: Type out exactly the 
      render: typescript
      placeholder: |
        Your code sample should be...
        ... Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        ... Complete - Provide all parts someone else needs to reproduce your problem
        ... Reproducible - Test the code you're about to provide to make sure it reproduces the problem

  - type: dropdown
    id: priority
    attributes:
      label: Priority this issue should have
      description: Please be realistic. If you need to elaborate on your reasoning, please use the Issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
