name: Suggestion
description: Do you have a suggestion for Azure? You can suggest it here
labels: [suggestion]
body:
  - type: markdown
    attributes:
      value: |
        Use Discord for questions: https://discord.gg/azurebot
        
  - type: textarea
    id: description
    attributes:
      label: Suggestion description
      description: |
        Describe the suggestion in as much detail as possible and tell us why you think it should be added to higher your odds

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files into it.
      placeholder: |
        There should be a game which allows us to use our cards. 
        We should be able to select 3 cards and then use their stats to fight. 
        After win you'd receive the card you fought against. 
        
        This should be added so its not just about collecting and trading.
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: How do you feel about your suggestion? How much value do you think it would add to the bot for you and other users? 
      description: Please be realistic. You can justify your choice in the field above
      options:
        - Little value (I can survive without it)
        - Great value (Would be cool to have)
        - Lot of value (Can't live without it)
    validations:
      required: true
